### ISSUE TITLE
HostMetadata calculated to be of `unknown` type as of latest release

### ISSUE THREAD

**Issue by jmaroeder** [cloudflare/workerd#483]
Hello, with the latest release of workers-types `4.20230321.0`, `HostMetadata` appears to be of `unknown` type, even when specifying a type as part of the parameters to `Request`.

Here is some example code which compiles fine with `4.20230228.0`:

```typescript
interface MyHostMetadata {
  foo: string;
}

let request: Request<MyHostMetadata> = new Request('');

console.log(request.cf?.hostMetadata.foo);
```

However, the latest version leads to the following error from `tsc`:
```
src/index.ts:7:13 - error TS18046: 'request.cf.hostMetadata' is of type 'unknown'.

7 console.log(request.cf?.hostMetadata.foo);
              ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mrbbot** [comment]
Hey! 👋 Apologies for the very delayed response on this. Looks like this got a little buried. 🙁 To explain what's going on here, this is a simplified snippet of the generated types:

```ts
declare class Request<CfHostMetadata = unknown, Cf = CfProperties<CfHostMetadata>> {
  get cf(): Cf | undefined;
}

declare type CfProperties<HostMetadata = unknown> =
  | IncomingRequestCfProperties<HostMetadata>
  | RequestInitCfProperties;

declare type IncomingRequestCfProperties<HostMetadata = unknown> =
    IncomingRequestCfPropertiesBase
  & IncomingRequestCfPropertiesCloudflareForSaaSEnterprise<HostMetadata>;
declare interface IncomingRequestCfPropertiesBase extends Record<string, unknown> {
  // ...
}
declare interface IncomingRequestCfPropertiesCloudflareForSaaSEnterprise<HostMetadata> {
  hostMetadata: HostMetadata;
}

declare interface RequestInitCfProperties extends Record<string, unknown> {
  // ...
}
```

We wanted users to be able to specify a custom `cf` type. Ideally, this should be the only type parameter of `Request`, but we already had a `CfHostMetadata` parameter and didn't want to break existing users (clearly we did anyways! 😅). Instead, we default the `Cf` type to either incoming/outgoing `cf` properties, since we don't know if this is an incoming/outgoing request. Both incoming (`IncomingRequestCfProperties`) and outgoing (`RequestInitCfProperties`) `cf` properties extend `Record<string, unknown>`, allowing for custom `cf` properties to be defined when calling service binding `fetch()`es. This means that the `Cf` type of `Request<MyHostMetdata>` is actually `CfProperties<MyHostMetdata>`, which is roughly `Record<string, unknown> | { hostMetadata: MyHostMetdata }`. So accessing `hostMetadata` gives you `unknown` instead, because `CfProperties` could've been `Record<string, unknown>`.

I think this behaviour is correct, if a little counter-intuitive. The fix here is to specify a second `Cf` type argument to the `Request` type, constraining it to incoming `cf` properties:

```ts
let request: Request<MyHostMetadata, IncomingRequestCfProperties<MyHostMetadata>> = new Request('');
```

We could automatically infer that you meant `IncomingRequestCfProperties` if a custom `CfHostMetadata` type parameter was specified, but I think the correct solution is just to remove the `CfHostMetadata` type parameter in favour of the more generic `Cf`. We'll do this in the next major version of `@cloudflare/workers-types`. 👍
